# fly.toml app configuration file generated for aucc-staging-green-sun-7553 on 2025-03-11T10:13:30+13:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aucc-staging-green-sun-7553'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
