# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --app aucc-staging 
      # \
      #     --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
      #     --build-arg PAYLOAD_SECRET=${{ secrets.PAYLOAD_SECRET }} \
      #     --build-arg SERVER_URL=${{ secrets.SERVER_URL }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}


# name: Fly Deploy

# on:
#   push:
#     branches:
#       - develop  # Deploy to Staging
#       - main     # Deploy to Production

# jobs:
#   deploy:
#     name: Deploy to Fly.io
#     runs-on: ubuntu-latest
#     concurrency: deploy-group  # Ensures only one deployment runs at a time

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v4

#       - name: Install Fly.io CLI
#         uses: superfly/flyctl-actions/setup-flyctl@master

#       - name: Set Fly.io App Name
#         run: |
#           if [ "${{ github.ref }}" == "refs/heads/develop" ]; then
#             echo "FLY_APP=aucc-staging" >> $GITHUB_ENV
#           elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
#             echo "FLY_APP=aucc-production" >> $GITHUB_ENV
#           else
#             echo "Branch not configured for deployment."
#             exit 1
#           fi

#       - name: Deploy to Fly.io
#         env:
#           FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
#         run: |
#           flyctl deploy --remote-only --app $FLY_APP
